// REDUX ACTION TYPES
export const GET_LIST_STUDIO = 'GET_LIST_STUDIO'
export const GET_LIST_STUDIO_ERROR = 'GET_LIST_STUDIO_ERROR'
export const GET_LIST_STUDIO_SUCCESS = 'GET_LIST_STUDIO_SUCCESS'
export const GET_LIST_STUDIO_LOADING = 'GET_LIST_STUDIO_LOADING'

export const GET_LIST_DURATION = 'GET_LIST_DURATION'
export const GET_LIST_DURATION_ERROR = 'GET_LIST_DURATION_ERROR'
export const GET_LIST_DURATION_SUCCESS = 'GET_LIST_DURATION_SUCCESS'
export const GET_LIST_DURATION_LOADING = 'GET_LIST_DURATION_LOADING'

export const GET_LIST_BOOKING = 'GET_LIST_BOOKING'
export const GET_LIST_BOOKING_ERROR = 'GET_LIST_BOOKING_ERROR'
export const GET_LIST_BOOKING_SUCCESS = 'GET_LIST_BOOKING_SUCCESS'
export const GET_LIST_BOOKING_LOADING = 'GET_LIST_BOOKING_LOADING'

export const GET_CALENDAR_ERROR = 'GET_CALENDAR_ERROR'
export const GET_CALENDAR_SUCCESS = 'GET_CALENDAR_SUCCESS'
export const GET_CALENDAR_LOADING = 'GET_CALENDAR_LOADING'

export const POST_BOOKING_ERROR = 'POST_BOOKING_ERROR'
export const POST_BOOKING_SUCCESS = 'POST_BOOKING_SUCCESS'
export const POST_BOOKING_LOADING = 'POST_BOOKING_LOADING'

export const GET_LIST_TIMESLOT_BYPARAMS_ERROR = 'GET_LIST_TIMESLOT_BYPARAMS_ERROR'
export const GET_LIST_TIMESLOT_BYPARAMS_SUCCESS = 'GET_LIST_TIMESLOT_BYPARAMS_SUCCESS'
export const GET_LIST_TIMESLOT_BYPARAMS_LOADING = 'GET_LIST_TIMESLOT_BYPARAMS_LOADING'

export const GET_LIST_STARTTIME_ERROR = 'GET_LIST_STARTTIME_ERROR'
export const GET_LIST_STARTTIME_SUCCESS = 'GET_LIST_STARTTIME_SUCCESS'
export const GET_LIST_STARTTIME_LOADING = 'GET_LIST_STARTTIME_LOADING'

export const POST_CHECK_BOOKING_ERROR = 'POST_CHECK_BOOKING_ERROR'
export const POST_CHECK_BOOKING_SUCCESS = 'POST_CHECK_BOOKING_SUCCESS'
export const POST_CHECK_BOOKING_LOADING = 'POST_CHECK_BOOKING_LOADING'

export const POST_CHECK_PAYMENT_STATUS_ERROR = 'POST_CHECK_PAYMENT_STATUS_ERROR'
export const POST_CHECK_PAYMENT_STATUS_SUCCESS = 'POST_CHECK_PAYMENT_STATUS_SUCCESS'
export const POST_CHECK_PAYMENT_STATUS_LOADING = 'POST_CHECK_PAYMENT_STATUS_LOADING'

export const GET_TOTAL_PRICE_ERROR = 'GET_TOTAL_PRICE_ERROR'
export const GET_TOTAL_PRICE_SUCCESS = 'GET_TOTAL_PRICE_SUCCESS'
export const GET_TOTAL_PRICE_LOADING = 'GET_TOTAL_PRICE_LOADING'

export const POST_CHECK_PROMOTION_BOOKING_ERROR = 'POST_CHECK_PROMOTION_BOOKING_ERROR'
export const POST_CHECK_PROMOTION_BOOKING_SUCCESS = 'POST_CHECK_PROMOTION_BOOKING_SUCCESS'
export const POST_CHECK_PROMOTION_BOOKING_LOADING = 'POST_CHECK_PROMOTION_BOOKING_LOADING'

export const SCROLL_TO_SEC_2 = 'SCROLL_TO_SEC_2'
export const SCROLL_TO_CONTACT = 'SCROLL_TO_CONTACT'
export const SCROLL_TO_ID = 'SCROLL_TO_ID'
export const LOADING = 'LOADING'
export const CLEAR_DATA = 'CLEAR_DATA'
